### ISSUE TITLE
Use with v4 of Varnish

### ISSUE THREAD

**Issue by djerfy** [cosimo/vlogdump#3]
Hi,

The varnishlog of Varnish v4 no longer operates in the same manner.
An update is planned ?

Best regards !

**Comment by lukaszlach** [comment]
Just a notice - vlogdump works nicely with Varnish 5.2. The only thing that needs fixing is header values being trimmed out of last character, I have modified `substr` call and it's done.

**Comment by cosimo** [comment]
Nice, thanks @lukaszlach. Can you please copy here your patch?

**Comment by cosimo** [comment]
Varnishlog for 4.x is now quite different, so I worked on a varnish4 branch, and the version of `vlogdump` there is probably not 100%, but it works well enough.
